2024-05-18 18:53:43,568 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 18:53:43,569 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Configure stats pid to 6249
2024-05-18 18:53:43,570 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-18 18:53:43,570 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/MiniGPT/wandb/settings
2024-05-18 18:53:43,571 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 18:53:43,571 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 18:53:43,572 INFO    MainThread:6249 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-18 18:53:43,573 INFO    MainThread:6249 [wandb_init.py:_log_setup():520] Logging user logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185343-41ezbu7b/logs/debug.log
2024-05-18 18:53:43,574 INFO    MainThread:6249 [wandb_init.py:_log_setup():521] Logging internal logs to /content/drive/MyDrive/MiniGPT/wandb/run-20240518_185343-41ezbu7b/logs/debug-internal.log
2024-05-18 18:53:43,574 INFO    MainThread:6249 [wandb_init.py:init():560] calling init triggers
2024-05-18 18:53:43,575 INFO    MainThread:6249 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-18 18:53:43,575 INFO    MainThread:6249 [wandb_init.py:init():610] starting backend
2024-05-18 18:53:43,576 INFO    MainThread:6249 [wandb_init.py:init():614] setting up manager
2024-05-18 18:53:43,581 INFO    MainThread:6249 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 18:53:43,582 INFO    MainThread:6249 [wandb_init.py:init():622] backend started and connected
2024-05-18 18:53:43,596 INFO    MainThread:6249 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-18 18:53:43,925 INFO    MainThread:6249 [wandb_init.py:init():711] updated telemetry
2024-05-18 18:53:43,976 INFO    MainThread:6249 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 18:53:47,222 WARNING MainThread:6249 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
